name: flutter_blueprint
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.2
  email_validator: ^1.0.6
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^4.0.4+1
  flutter_secure_storage: ^4.0.0
  formz: ^0.3.2
  geocoder: ^0.2.1
  geolocator: ^6.1.14
  get: ^3.26.0
  google_fonts: any
  logger: ^0.9.4
  permission_handler: ^5.1.0+2
  pull_to_refresh: ^1.6.4


dev_dependencies:
  change_app_package_name: ^0.1.2
  # native icons & splash
  flutter_launcher_icons: any
  flutter_native_splash: any
  flutter_test:
    sdk: flutter

# flutter icons setup
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# flutter splash screen setup
flutter_native_splash:
  image: assets/img/splash.png
  color: "#FFEB3B"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
