on:
  push:
    branches:
      - master
name: Code checker
jobs:
  build:
    name: Code checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - run: flutter clean
      - run: flutter pub upgrade
      - run: flutter pub get
#      - run: flutter pub run build_runner build
      - run: flutter analyze
      - run: flutter build apk
      - uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Deploy
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: HeatDance
          releaseNotes: "AloneCall from GitHub Action"
          file: build/app/outputs/flutter-apk/app-release.apk
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: apk-release